
blank_issues_enabled: false
contact_links:
  - name: Banks o' Dee FC Support
    url: https://banksofdee.co.uk/contact
    about: Please contact support for questions that are not bug reports or feature requests
