
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { publicEnv } from '@/lib/env';

// Use environment variables from our utilities
const SUPABASE_URL = publicEnv.getSupabaseUrl();
const SUPABASE_PUBLISHABLE_KEY = publicEnv.getSupabaseAnonKey();

// Log warnings if environment variables are missing
if (!SUPABASE_URL || SUPABASE_URL === '') {
  console.warn('Warning: NEXT_PUBLIC_SUPABASE_URL is not set in environment variables. Using fallback value.');
}

if (!SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY === '') {
  console.warn('Warning: NEXT_PUBLIC_SUPABASE_ANON_KEY is not set in environment variables. Using fallback value.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
