// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { env } from '@/lib/env';

// Use environment variables from our utilities
const getSupabaseUrl = () => {
  const url = env.supabase.url;
  if (!url) {
    console.error('Critical Error: NEXT_PUBLIC_SUPABASE_URL is not set in environment variables');
    return 'https://bbbxhwaixjjxgboeiktq.supabase.co'; // Fallback for development only
  }
  return url;
};

const getSupabaseKey = () => {
  const key = env.supabase.anonKey;
  if (!key) {
    console.error('Critical Error: NEXT_PUBLIC_SUPABASE_ANON_KEY is not set in environment variables');
    // Providing a fallback for development environments only
    return 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJiYnhod2FpeGpqeGdib2Vpa3RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MzA1NzMsImV4cCI6MjA1ODQwNjU3M30.ZZEenwbdq-bGlya3R2yvuspOlKMqkBp6tzC3TAdKGcQ';
  }
  return key;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(getSupabaseUrl(), getSupabaseKey(), {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});
